name: Axolotl pipeline

on:
  push:
    branches:
      - main
    tags:
      - v
  pull_request:

jobs:

  build-crayfish:
    name: Build crayfish
    runs-on: ubuntu-latest

    steps:
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path Cargo.toml --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: crayfish
          path: target/release/crayfish
          retention-days: 1